# Generated by Django 2.2.26 on 2022-03-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0002_auto_20220305_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpaymentmethod',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='customerpaymentmethod',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Payment method id'),
        ),
        migrations.AddField(
            model_name='customerpaymentmethod',
            name='token_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Token ID'),
        ),
    ]
