# Generated by Django 2.2.26 on 2022-03-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0004_auto_20220306_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='status',
            field=models.CharField(choices=[('-1', 'incomplete'), ('0', 'inactive'), ('1', 'active')], default='-1', max_length=2),
        ),
    ]
