# Generated by Django 2.2.27 on 2022-03-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0005_auto_20220307_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepayment',
            name='is_cancel',
            field=models.CharField(choices=[('0', 'no'), ('1', 'yes')], default='0', max_length=2),
        ),
    ]
