# Generated by Django 2.2.28 on 2022-08-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0006_stripepayment_is_cancel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='status',
        ),
        migrations.RemoveField(
            model_name='stripepayment',
            name='status',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='is_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='payment_intent_client_secret',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment intent cliend secret'),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment intent id'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
