# Generated by Django 2.2.28 on 2022-08-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0007_auto_20220808_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='token_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token ID'),
        ),
    ]
