# Generated by Django 2.2.26 on 2022-02-15 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import students.common


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200, verbose_name='Student name')),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Height')),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Height')),
                ('dob', models.DateField(blank=True, default=None, null=True, verbose_name='Date of birth')),
                ('grade', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Grade')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('profile_image', models.ImageField(blank=True, default=0, null=True, upload_to=students.common.file_upload)),
                ('status', models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default=1, max_length=2)),
                ('saved_album_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SpecialService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Grade')),
                ('doc_title', models.CharField(max_length=100, verbose_name='Document title')),
                ('report_card', models.FileField(default=0, upload_to=students.common.file_upload, validators=[students.common.file_validation])),
                ('status', models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default=1, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_service', to='students.Student')),
            ],
            options={
                'verbose_name': 'Special Service',
                'verbose_name_plural': 'Special Services',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Grade')),
                ('doc_title', models.CharField(max_length=100, verbose_name='Document title')),
                ('report_card', models.FileField(default=0, upload_to=students.common.file_upload, validators=[students.common.file_validation])),
                ('status', models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default=1, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card', to='students.Student')),
            ],
            options={
                'verbose_name': 'Report Card',
                'verbose_name_plural': 'Report Cards',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OtherDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(max_length=100, verbose_name='Document title')),
                ('report_card', models.FileField(default=0, null=True, upload_to=students.common.file_upload, validators=[students.common.file_validation])),
                ('status', models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default=1, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_doc', to='students.Student')),
            ],
            options={
                'verbose_name': 'OtherDocument',
                'verbose_name_plural': 'OtherDocuments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(max_length=100, verbose_name='Document title')),
                ('report_card', models.FileField(default=0, upload_to=students.common.file_upload, validators=[students.common.file_validation])),
                ('status', models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default=1, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunization', to='students.Student')),
            ],
            options={
                'verbose_name': 'Immunization',
                'verbose_name_plural': 'Immunizations',
                'ordering': ['-id'],
            },
        ),
    ]
