# Generated by Django 2.2.26 on 2022-02-24 13:28

from django.db import migrations, models
import students.common


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunization',
            name='report_card',
            field=models.FileField(blank=True, null=True, upload_to=students.common.file_upload, validators=[students.common.file_validation]),
        ),
        migrations.AlterField(
            model_name='otherdocument',
            name='report_card',
            field=models.FileField(blank=True, null=True, upload_to=students.common.file_upload, validators=[students.common.file_validation]),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='report_card',
            field=models.FileField(blank=True, null=True, upload_to=students.common.file_upload, validators=[students.common.file_validation]),
        ),
        migrations.AlterField(
            model_name='specialservice',
            name='report_card',
            field=models.FileField(blank=True, null=True, upload_to=students.common.file_upload, validators=[students.common.file_validation]),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grade'),
        ),
    ]
