# Generated by Django 2.2.27 on 2022-03-17 17:12

from django.db import migrations, models
import django.db.models.deletion
import students.common


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20220227_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('status', models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default=1, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Special service category',
                'verbose_name_plural': 'Special service categories',
                'ordering': ['-id'],
            },
        ),
        migrations.RenameField(
            model_name='immunization',
            old_name='report_card',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='otherdocument',
            old_name='report_card',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='specialservice',
            old_name='report_card',
            new_name='document',
        ),
        migrations.RemoveField(
            model_name='student',
            name='saved_album_at',
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=students.common.file_upload),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grade')),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Height')),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Weight')),
                ('image', models.ImageField(blank=True, null=True, upload_to=students.common.file_upload)),
                ('status', models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default=1, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='students.Student')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='specialservice',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='special_service', to='students.SpecialServiceCategory'),
            preserve_default=False,
        ),
    ]
