# Generated by Django 2.2.28 on 2022-06-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20220317_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='height',
        ),
        migrations.AddField(
            model_name='student',
            name='height_feet',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Height Feet'),
        ),
        migrations.AddField(
            model_name='student',
            name='height_inch',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Height Inch'),
        ),
    ]
