# Generated by Django 2.2.28 on 2022-07-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20220622_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='status',
            field=models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='otherdocument',
            name='status',
            field=models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='status',
            field=models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='specialservice',
            name='status',
            field=models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='specialservicecategory',
            name='status',
            field=models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default='1', max_length=2),
        ),
    ]
