# Generated by Django 2.2.28 on 2022-08-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20220715_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='status',
        ),
        migrations.RemoveField(
            model_name='immunization',
            name='status',
        ),
        migrations.RemoveField(
            model_name='otherdocument',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reportcard',
            name='status',
        ),
        migrations.RemoveField(
            model_name='specialservice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='specialservicecategory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AddField(
            model_name='album',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='immunization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='otherdocument',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='specialservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='specialservicecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
